//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.01.06 at 09:08:09 AM UTC
//
package se.trixon.quakeml4j.v1_2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for DataUsedWaveType.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="DataUsedWaveType"&gt; &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&gt; &lt;enumeration value="P
 * waves"/&gt; &lt;enumeration value="body waves"/&gt; &lt;enumeration
 * value="surface waves"/&gt; &lt;enumeration value="mantle waves"/&gt;
 * &lt;enumeration value="combined"/&gt; &lt;enumeration value="unknown"/&gt;
 * &lt;/restriction&gt; &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "DataUsedWaveType")
@XmlEnum
public enum DataUsedWaveType {

    @XmlEnumValue("P waves")
    P_WAVES("P waves"),
    @XmlEnumValue("body waves")
    BODY_WAVES("body waves"),
    @XmlEnumValue("surface waves")
    SURFACE_WAVES("surface waves"),
    @XmlEnumValue("mantle waves")
    MANTLE_WAVES("mantle waves"),
    @XmlEnumValue("combined")
    COMBINED("combined"),
    @XmlEnumValue("unknown")
    UNKNOWN("unknown");
    private final String value;

    DataUsedWaveType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataUsedWaveType fromValue(String v) {
        for (DataUsedWaveType c : DataUsedWaveType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
