//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.01.06 at 09:08:09 AM UTC
//
@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://quakeml.org/xmlns/bed/1.2", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package se.trixon.quakeml4j.v1_2;
