//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.01.06 at 09:08:09 AM UTC
//
package se.trixon.quakeml4j.v1_2;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for AmplitudeCategory.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * <
 * pre>
 * &lt;simpleType name="AmplitudeCategory"&gt; &lt;restriction
 * base="{http://www.w3.org/2001/XMLSchema}string"&gt; &lt;enumeration
 * value="point"/&gt; &lt;enumeration value="mean"/&gt; &lt;enumeration
 * value="duration"/&gt; &lt;enumeration value="period"/&gt; &lt;enumeration
 * value="integral"/&gt; &lt;enumeration value="other"/&gt; &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 *
 */
@XmlType(name = "AmplitudeCategory")
@XmlEnum
public enum AmplitudeCategory {

    @XmlEnumValue("point")
    POINT("point"),
    @XmlEnumValue("mean")
    MEAN("mean"),
    @XmlEnumValue("duration")
    DURATION("duration"),
    @XmlEnumValue("period")
    PERIOD("period"),
    @XmlEnumValue("integral")
    INTEGRAL("integral"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    AmplitudeCategory(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AmplitudeCategory fromValue(String v) {
        for (AmplitudeCategory c : AmplitudeCategory.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
