//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2026.01.06 at 09:08:09 AM UTC
//
package se.trixon.quakeml4j.v1_2;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAnyAttribute;
import jakarta.xml.bind.annotation.XmlAnyElement;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.namespace.QName;
import org.w3c.dom.Element;

/**
 * <p>
 * Java class for NodalPlanes complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="NodalPlanes"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;element name="nodalPlane1" type="{http://quakeml.org/xmlns/bed/1.2}NodalPlane" minOccurs="0"/&gt;
 *           &lt;element name="nodalPlane2" type="{http://quakeml.org/xmlns/bed/1.2}NodalPlane" minOccurs="0"/&gt;
 *         &lt;/choice&gt;
 *         &lt;any processContents='lax' namespace='##other' maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="preferredPlane" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodalPlanes", propOrder = {
    "nodalPlane1OrNodalPlane2",
    "any"
})
public class NodalPlanes {

    @XmlElementRefs({
        @XmlElementRef(name = "nodalPlane1", namespace = "http://quakeml.org/xmlns/bed/1.2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "nodalPlane2", namespace = "http://quakeml.org/xmlns/bed/1.2", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<NodalPlane>> nodalPlane1OrNodalPlane2;
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "preferredPlane")
    protected BigInteger preferredPlane;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the nodalPlane1OrNodalPlane2 property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the nodalPlane1OrNodalPlane2 property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodalPlane1OrNodalPlane2().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null null
     * null null     {@link JAXBElement }{@code <}{@link NodalPlane }{@code >}
     * {@link JAXBElement }{@code <}{@link NodalPlane }{@code >}
     *
     *
     */
    public List<JAXBElement<NodalPlane>> getNodalPlane1OrNodalPlane2() {
        if (nodalPlane1OrNodalPlane2 == null) {
            nodalPlane1OrNodalPlane2 = new ArrayList<JAXBElement<NodalPlane>>();
        }
        return this.nodalPlane1OrNodalPlane2;
    }

    /**
     * Gets the value of the any property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the any property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list null null null
     * null null     {@link Element }
     * {@link Object }
     *
     *
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the preferredPlane property.
     *
     * @return possible object is {@link BigInteger }
     *
     */
    public BigInteger getPreferredPlane() {
        return preferredPlane;
    }

    /**
     * Sets the value of the preferredPlane property.
     *
     * @param value allowed object is {@link BigInteger }
     *
     */
    public void setPreferredPlane(BigInteger value) {
        this.preferredPlane = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed
     * property on this class.
     *
     * <p>
     * the map is keyed by the name of the attribute and the value is the string
     * value of the attribute.
     *
     * the map returned by this method is live, and you can add new attribute by
     * updating the map directly. Because of this design, there's no setter.
     *
     *
     * @return always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
